---
title: "analysis"
author: "Jaden Orli"
date: "2023-03-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(RColorBrewer)
library(caret)
library(ggpubr)
library(MASS)
library(lme4)
source("my_functions.R")
setup_libs()

display.brewer.all(colorblindFriendly = TRUE)
```


#1. Set up 

### a) Color Palette
```{r}
#choose a color palette
#display.brewer.pal(n = 8, name = 'OrRd')
#brewer.pal(n = 8, name = "OrRd")

#assign colors to names
adults = "#D7301F"
juveniles = "#FDBB84"
totals  = "#990000"
nico_eggs = "#FCC5C0"
crab_eggs = "#EF6548"
```


### b) Dataframes
```{r}
#read in the latest of the egg mortality data 
egg_mortality <- read_csv("NicothoidProjectAnalysis/RawData/eggmortalitydata.csv") %>% 
  clean_names() %>%
  select(!16:18) %>% 
  filter(!is.na(pleopod_number)) %>%
  filter(!eds == "M") %>%
  mutate(prop_viable_eggs = number_viable_crab_eggs/total_number_crab_eggs) %>% 
  mutate(prop_nonviable_eggs = total_number_non_viable_crab_eggs/total_number_crab_eggs) %>%
  mutate(total_nicos = (number_adult_nicos + number_juvenile_nicos)) 

#read in the egg mortality data that has development days
egg_mortality_day <- read_csv("NicothoidProjectAnalysis/RawData/eggmortality_day.csv") %>% 
  clean_names() %>%
  select(!17:19) %>% 
  filter(!is.na(pleopod_number)) %>%
  filter(!eds == "M") %>%
  mutate(prop_viable_eggs = number_viable_crab_eggs/total_number_crab_eggs) %>% 
  mutate(prop_nonviable_eggs = total_number_non_viable_crab_eggs/total_number_crab_eggs)

```


# 2. Timeseries Visualization

### a) Egg Mortality Data by EDS 
```{r}
#visualize the change in proportion of viable eggs over time
#subset the data with the desireds columns
egg_mort_viable <- egg_mortality %>%
  select(4,16)


#plot the data for the longer dataframe with the averages as groups
eggs_mort_eds_vis <- ggplot(data = egg_mort_viable, 
       aes(x = eds, y = prop_viable_eggs)) +
  geom_point(color = crab_eggs) +
  theme_gray() +
  geom_smooth(method = lm, level = 0.95, color = "black") +
  ylab("Proportion Viable Crab Eggs") +
  xlab("Egg Development Stage (EDS)") + 
  ggtitle("Egg Mortality Across EDS") +
  theme(plot.title = element_text(hjust = 0.5))

#create a data frame with the average values across each EDS 
eggs_mort_eds_avg <- eggs_mort_all %>%
  group_by(eds) %>%
  summarize(avg_prop_viable_eggs = mean(prop_viable_eggs),
            avg_prop_nonviable_eggs = mean(prop_nonviable_eggs)) %>%
  as_tibble()


#plot the data for the dataframe with the averages as groups
eggs_mort_eds_avg_vis <- ggplot(data = eggs_mort_eds_avg, 
       aes(x = eds, y = avg_prop_viable_eggs)) +
  geom_point(color = crab_eggs) +
  theme_gray() +
  geom_smooth(method = lm, level = 0.95, color = "black") +
  ylab("Average Proportion Viable Crab Eggs") +
  xlab("Egg Development Stage (EDS)") + 
  ggtitle("Average Egg Mortality Across EDS") +
  theme(plot.title = element_text(hjust = 0.5))


#remove the most highly infested crabs (037, 043, and 045)
new_crab_eds <- egg_mortality %>%
  filter(!crab_id == "ANT-GAV-037") %>%
  filter(!crab_id == "ANT-GAV-045") %>%
  filter(!crab_id == "ANT-GAV-043")

#create a data frame with the average values across each day 
eggs_mort_avg_new_eds <- new_crab_eds %>%
  group_by(eds) %>%
  summarize(avg_prop_viable_eggs = mean(prop_viable_eggs),
            avg_prop_nonviable_eggs = mean(prop_nonviable_eggs)) %>%
  as_tibble()

#plot the data for the longer dataframe with the averages as groups
eggs_mort_vis_new_eds <- ggplot(data = eggs_mort_avg_new_eds, 
       aes(x = eds, y = avg_prop_viable_eggs)) +
  geom_point(color= crab_eggs) +
  theme_gray() +
  geom_smooth(method = lm, level = 0.95, color = "black") +
  ylab("Average Proportion Viable Crab Eggs") +
  xlab("Egg Development Stage (EDS)") + 
  ggtitle("Egg Mortality Across EDS (excluding highly infested hosts)") +
  theme(plot.title = element_text(hjust = 0.5))

#plot the graphs
eggs_mort_eds_vis
eggs_mort_eds_avg_vis
eggs_mort_vis_new_eds

```


### b) Egg Mortality Data by Development Day
```{r}
#create a data frame with the average values across each EDS 
eggs_mort_day_avg <- egg_mortality_day %>%
  group_by(day) %>%
  summarize(avg_prop_viable_eggs = mean(prop_viable_eggs),
            avg_prop_nonviable_eggs = mean(prop_nonviable_eggs)) %>%
  as_tibble()

#pivot the data longer 
eggs_mort_day_long <- eggs_mort_day_avg %>%
  pivot_longer(names_to = "averages",
               cols = c("avg_prop_viable_eggs", "avg_prop_nonviable_eggs"))


#plot the data for the  dataframe with the averages as groups
eggs_mort_day_vis <- ggplot(data = eggs_mort_day_avg, 
       aes(x = day, y = avg_prop_viable_eggs)) +
  geom_point(color= crab_eggs) +
  theme_gray() +
  geom_smooth(method = lm, level = 0.95, color = "black") +
  ylab("Average Proportion Viable Crab Eggs") +
  xlab("Development Day") + 
  ggtitle("Egg Mortality Across Development Days") +
  theme(plot.title = element_text(hjust = 0.5))

#remove the most highly infested crabs (037, 043, and 045)
new_crab <- egg_mortality_day %>%
  filter(!crab_id == "ANT-GAV-037") %>%
  filter(!crab_id == "ANT-GAV-045") %>%
  filter(!crab_id == "ANT-GAV-043")

#create a data frame with the average values across each day 
eggs_mort_avg_new <- new_crab %>%
  group_by(day) %>%
  summarize(avg_prop_viable_eggs = mean(prop_viable_eggs),
            avg_prop_nonviable_eggs = mean(prop_nonviable_eggs)) %>%
  as_tibble()

#plot the data for the longer dataframe with the averages as groups
eggs_mort_vis_new <- ggplot(data = eggs_mort_avg_new, 
       aes(x = day, y = avg_prop_viable_eggs)) +
  geom_point(color= crab_eggs) +
  theme_gray() +
  geom_smooth(method = lm, level = 0.95, color = "black") +
  ylab("Average Proportion Viable Crab Eggs") +
  xlab("Development Day") + 
  ggtitle("Egg Mortality Across Development Days (excluding highly infested hosts)") +
  theme(plot.title = element_text(hjust = 0.5))

#plot the two graphs
eggs_mort_day_vis
eggs_mort_vis_new

```


# 3. Counts Visualization
```{r}
#plot the number of adult nicos against the total number of viable eggs
adult_plot <- ggplot(data = egg_mortality, 
       aes( x = prop_viable_eggs, y = number_adult_nicos)) +
  geom_point(color = adults) + 
  geom_smooth(method = lm, level = 0.95, color = "black") +
  theme_gray() +
  ylab("Counts") +
  xlab("Proportion of Viable Crab Eggs") + 
  ggtitle("Adult Nicos") +
  theme(plot.title = element_text(hjust = 0.5))

#plot the number of juvenile nicos against the total number of viable eggs 
juvenile_plot <- ggplot(data = egg_mortality, 
       aes(x = prop_viable_eggs, y = number_juvenile_nicos)) +
  geom_point(color = juveniles) + 
  geom_smooth(method = lm, level = 0.95, color = "black") +
  theme_gray() +
  ylab("Counts") +
  xlab("Proportion of Viable Crab Eggs") + 
  ggtitle("Juvenile Nicos") +
  theme(plot.title = element_text(hjust = 0.5)) 

#plot the number of total number of nicos against the total number of viable eggs
total_plot <- ggplot(data = egg_mortality, 
       aes( x = prop_viable_eggs, y = total_nicos)) +
  geom_point(color = totals) + 
  geom_smooth(method = lm, level = 0.95, color = "black") +
  theme_gray() +
  ylab("Counts") +
  xlab("Proportion of Viable Crab Eggs") + 
  ggtitle("Total Nicos") +
  theme(plot.title = element_text(hjust = 0.5))


#plot the number of nico eggs against the total number of viable eggs
nico_egg_plot <- ggplot(data = egg_mortality, 
       aes(x = prop_viable_eggs, y = number_nico_eggs)) +
  geom_point(color = nico_eggs) + 
  geom_smooth(method = lm, level = 0.95, color = "black") +
  theme_gray() +
  ylab("Counts") +
  xlab("Proportion of Viable Crab Eggs") + 
  ggtitle("Number Nico Eggs") +
  theme(plot.title = element_text(hjust = 0.5)) 

ggarrange(adult_plot, juvenile_plot, total_plot, nico_egg_plot,
                           labels = c("a)", "b)", "c)", "d)"),
                           ncol = 2, nrow = 2)



## we see that there is a clear relationship between the proportion of nonviable eggs and the number of nico eggs while there isn't always this clear relationship with the total number of nicos and the proportion of nonviable eggs
## this is why I want to do things in terms of biomass because the adult nicos are transforming the crab egg biomass directly into nico egg biomass
```

# 4. Visually Evaluate Normality
```{r}
#look at the frequency of the count data for all the life stages

#plot the frequency of adult nicos 
adult_plot_hist <- gghistogram(data = egg_mortality, 
                               x = "number_adult_nicos", 
                               fill = adults) +
  theme_gray() +
  ylab("Counts") +
  xlab("Frequency") + 
  ggtitle("Adult Nicos") +
  theme(plot.title = element_text(hjust = 0.5))

#plot the frequency of juvenile nicos 
juvenile_plot_hist <- gghistogram(data = egg_mortality, 
                               x = "number_juvenile_nicos",
                               fill = juveniles) +
  theme_gray() +
  ylab("Counts") +
  xlab("Frequency") + 
  ggtitle("Juvenile Nicos") +
  theme(plot.title = element_text(hjust = 0.5))

#plot the frequency of total nicos 
total_plot_hist <- gghistogram(data = egg_mortality, 
                               x = "total_nicos",
                               fill = totals) +
  theme_gray() +
  ylab("Counts") +
  xlab("Frequency") + 
  ggtitle("Total Nicos") +
  theme(plot.title = element_text(hjust = 0.5))


#plot the frequency of juvenile nicos 
nico_eggs_plot_hist <- gghistogram(data = egg_mortality, 
                               x = "number_nico_eggs",
                               fill = nico_eggs) +
  theme_gray() +
  ylab("Counts") +
  xlab("Frequency") + 
  ggtitle("Nicos Eggs") +
  theme(plot.title = element_text(hjust = 0.5))

#combine the plots 
ggarrange(adult_plot_hist, juvenile_plot_hist, total_plot_hist, nico_eggs_plot_hist,
                           labels = c("a)", "b)", "c)", "d)"),
                           ncol = 2, nrow = 2)

## it is obvious that the count data is heavily right skewed
```



# 5. Analysis

### a) Generalized Linear Models
```{r}
#create a generalized linear model to evaluate the relationship between viable eggs and number of adult nicos

##poisson 
glm.adults.poisson <- glmer(number_viable_crab_eggs ~ number_adult_nicos + (1|crab_id), 
                   data = egg_mortality, 
                   family = "poisson")

##negative binomial 
glm.adults.nb <- glmer.nb(number_viable_crab_eggs ~ number_adult_nicos + (1|crab_id), 
                   data = egg_mortality)

#create a generalized linear model to evaluate the relationship between viable eggs and number of juvenile nicos

##poisson 
glm.juveniles.poisson <- glmer(number_viable_crab_eggs ~ number_juvenile_nicos + (1|crab_id), 
                   data = egg_mortality, 
                   family = "poisson")

##negative binomial 
glm.juveniles.nb <- glmer.nb(number_viable_crab_eggs ~ number_juvenile_nicos + (1|crab_id), 
                   data = egg_mortality)

#create a generalized linear model to evaluate the relationship between viable eggs and number of nicos eggs

##poisson 
glm.nicoeggs.poisson <- glmer(number_viable_crab_eggs ~ number_nico_eggs + (1|crab_id), 
                   data = egg_mortality, 
                   family = "poisson")

##negative binomial 
glm.nicoeggs.nb <- glmer.nb(number_viable_crab_eggs ~ number_nico_eggs + (1|crab_id), 
                   data = egg_mortality)

#evaluate with interactions of all of the states

##poisson 
glm.combined.poisson <- glmer(number_viable_crab_eggs ~ number_adult_nicos*number_juvenile_nicos*number_nico_eggs + (1|crab_id), 
                   data = egg_mortality, 
                   family = "poisson")

##negative binomial 
glm.combined.nb <- glmer.nb(number_viable_crab_eggs ~ number_adult_nicos*number_juvenile_nicos*number_nico_eggs + (1|crab_id), 
                   data = egg_mortality)

```



### b). Mean Density
```{r}
#create a data frame with density of the adults in the egg mas per 
egg_mortality_density <- egg_mortality %>%
  mutate(density_adult_nicos = (number_adult_nicos/total_number_crab_eggs)) %>%
  mutate(density_juvenile_nicos = (number_juvenile_nicos/total_number_crab_eggs)) %>%
  mutate(density_total_nicos = (total_nicos/total_number_crab_eggs)) %>%
  mutate(density_nico_eggs = (number_nico_eggs/total_number_crab_eggs))

#calculate the mean density of each of the values 
## do I need to multiply these values by 1000? How do we get it to mean density per 1000 eggs?
mean_adult_density <- mean(egg_mortality_density$density_adult_nicos)
mean_adult_density

mean_juvenile_density <- mean(egg_mortality_density$density_juvenile_nicos)
mean_juvenile_density

mean_total_density <- mean(egg_mortality_density$density_total_nicos)
mean_total_density

mean_nico_egg_density <- mean(egg_mortality_density$density_nico_eggs)
mean_nico_egg_density



```


### c) Mean Intensity 
```{r}

```

