---
title: "DataVis"
output: html_document
date: "2023-01-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(RColorBrewer)
library(caret)
source("my_functions.R")
setup_libs()

display.brewer.all(colorblindFriendly = TRUE)
```

#1.Egg Mort Data 

Looking at egg mortality from winter 2023
- 9 crabs
- egg dev varied from G to spawn
- we think that number of adult nicos will directly affect egg mortality

## 1.a) First Visualization
```{r visualize egg mortality data}
eggs <- read_csv("NicothoidProjectAnalysis/RawData/eggmortality_w2023.csv") %>% 
  clean_names() %>% 
  select(!16:27) %>% 
  mutate(prop_viable_eggs = number_viable_crab_eggs/total_number_crab_eggs) %>% 
  mutate(prop_nonviable = total_number_non_viable_crab_eggs/total_number_crab_eggs)

nico_v_eggs <- ggplot(data = eggs, aes(x = number_adult_nicos, y = prop_viable_eggs)) +
  geom_point()

nico_v_nveggs <- ggplot(data = eggs, aes(x = number_adult_nicos, y = prop_nonviable)) +
  geom_point()

```


## 1.b) Second Visualization 
```{r, visualize full first trial of egg mort data}
#create an eggs_mort_all dataframe with columns for the prop of the values at that time
eggs_mort_all <- read_csv("NicothoidProjectAnalysis/RawData/eggmortality2.csv")%>% 
  clean_names() %>%
  select(!16:18) %>% 
  filter(!is.na(pleopod_number)) %>%
  filter(!eds == "M") %>%
  mutate_at(c(6:15), as.numeric) %>%
  mutate(prop_viable_eggs = number_viable_crab_eggs/total_number_crab_eggs) %>% 
  mutate(prop_nonviable_eggs = total_number_non_viable_crab_eggs/total_number_crab_eggs)%>%
  mutate(prop_damaged_eggs = number_damaged_crab_eggs/total_number_crab_eggs) %>%
  mutate(prop_stunted_eggs = number_stunted_crab_eggs/total_number_crab_eggs) %>%
  mutate(log_adult_nicos = log10(number_adult_nicos)) %>%
  mutate(log_juvenile_nicos = log10(number_juvenile_nicos)) %>%
  mutate(log_nico_eggs = log10(number_nico_eggs))

```


```{r, visualize full first trial of egg mort data}
#create a data frame with the average values across each EDS 
eggs_mort_avg <- eggs_mort_all %>%
  group_by(eds) %>%
  summarize(avg_prop_viable_eggs = mean(prop_viable_eggs),
            avg_prop_nonviable_eggs = mean(prop_nonviable_eggs),
            avg_prop_damaged_eggs = mean(prop_damaged_eggs),
            avg_prop_stunted_eggs = mean(prop_stunted_eggs),
            avg_log_adult_nicos = mean(log_adult_nicos),
            avg_log_juvenile_nicos = mean(log_juvenile_nicos),
            avg_log_nico_eggs = mean(log_nico_eggs)) %>%
  as_tibble()

#pivot the data longer 
eggs_mort_long <- eggs_mort_avg %>%
  pivot_longer(names_to = "averages",
               cols = c("avg_prop_viable_eggs" : "avg_log_nico_eggs"))


#plot the data for the longer dataframe with the averages as groups
eggs_mort_vis <- ggplot(data = eggs_mort_long, 
       aes(x = eds, y = value, group = averages, col = averages)) +
  scale_fill_brewer(palette = "Paired",
                     name = "Legend") +
  geom_point() +
  geom_line() +
  theme_gray() +
  ylab("Average Proportion") +
  xlab("Egg Development Stage") + 
  ggtitle("Egg Mortality Across Egg Development Stages") +
  theme(plot.title = element_text(hjust = 0.5))

eggs_mort_vis
```



```{r}
##try averaging the values then log transforming 
eggs_mort_avg_new <- eggs_mort_all %>%
  group_by(eds) %>%
  summarize(avg_prop_viable_eggs = mean(prop_viable_eggs),
            avg_prop_nonviable_eggs = mean(prop_nonviable_eggs),
            avg_prop_damaged_eggs = mean(prop_damaged_eggs),
            avg_prop_stunted_eggs = mean(prop_stunted_eggs),
            avg_number_adult_nicos = mean(number_adult_nicos),
            avg_number_juvenile_nicos = mean(number_juvenile_nicos),
            avg_number_nico_eggs = mean(number_nico_eggs)) %>%
  mutate(log_avg_adult_nicos = log10(avg_number_adult_nicos)) %>%
  mutate(log_avg_juvenile_nicos = log10(avg_number_juvenile_nicos)) %>%
  mutate(log_avg_nico_eggs = log10(avg_number_nico_eggs)) %>%
  as_tibble()

##pivot the data longer 
eggs_mort_long_new <- eggs_mort_avg_new %>%
  select(1,3, 9:11) %>%
  pivot_longer(names_to = "averages",
               cols = c("avg_prop_nonviable_eggs" : "log_avg_nico_eggs"))


#plot the data for the longer dataframe with the averages as groups
eggs_mort_vis_new <- ggplot(data = eggs_mort_long_new, 
       aes(x = eds, y = value, group = averages, col = averages)) +
  scale_fill_brewer(palette = "Paired",
                     name = "Legend") +
  geom_point() +
  geom_line() +
  theme_gray() +
  ylab("Average Proportion") +
  xlab("Egg Development Stage") + 
  ggtitle("Egg Mortality Across Egg Development Stages") +
  theme(plot.title = element_text(hjust = 0.5))

eggs_mort_vis_new

```


#2.Autoinfection Data 

##2.a) Visualize All
```{r, visualize autoinfeciton data}
#create an autoinfection_all dataframe with columns for the prop of the values at that time
autoinfection_all <- read_csv("NicothoidProjectAnalysis/RawData/autoinfection_all.csv") %>%
  clean_names() %>% 
  mutate(prop_viable_eggs = number_viable_crab_eggs/total_number_crab_eggs) %>% 
  mutate(prop_nonviable_eggs = number_nonviable_crab_eggs/total_number_crab_eggs) %>%
  mutate(log_normal_adult_copepods = log10(number_adult_copepods)) %>%
  mutate(log_normal_copepod_eggs = log10(number_copepod_eggs))

#create a data frame with the average values across each EDS 
autoinfection_avg <- autoinfection_all %>%
  group_by(egg_development_stage) %>%
  summarize(avg_prop_nonviable_eggs = mean(prop_nonviable_eggs),
            avg_prop_viable_eggs = mean(prop_viable_eggs),
            avg_log_adult_copepods = mean(log_normal_adult_copepods),
            avg_log_copepod_eggs = mean(log_normal_copepod_eggs)) %>%
  as_data_frame()

#pivot the data longer 
auotinfection_long <- autoinfection_avg %>%
  pivot_longer(names_to = "averages",
               cols = c("avg_prop_nonviable_eggs" : "avg_log_copepod_eggs"))

as.numeric(auotinfection_long$averages)

#create a good color palette
#look at the colorblind palette and decide on some good colors for a custom palette
nico_colors <- brewer.pal(n = 9, name = "OrRd")


#plot the data for the longer dataframe with the averages as groups
autoinfection_vis <- ggplot(data = auotinfection_long, 
       aes(x = egg_development_stage, y = value, group = averages, col = averages)) +
  scale_color_manual(values = c("#FDD49E","#EF6548","#B30000", "#7F0000"),
                     labels = c("Adult Copepods", "Copepod Eggs", "Nonviable Eggs", "Viable Eggs" ),
                     name = "Legend") +
  geom_point() +
  geom_line() +
  theme_gray() +
  ylab("Average Proportion") +
  xlab("Egg Development Stage") + 
  ggtitle("Autoinfection Across Egg Development Stages") +
  theme(plot.title = element_text(hjust = 0.5))

autoinfection_vis

```


##2.b) Visualize by Crab
```{r}
#zoe added onto this code to group first by INDIVIDUAL CRAB and then by EDS
autoinfection_crabmeans <- autoinfection_all %>%
  group_by(crab_id, egg_development_stage) %>%
  summarize(avg_prop_nonviable_eggs = mean(prop_nonviable_eggs),
            avg_prop_viable_eggs = mean(prop_viable_eggs),
            avg_prop_adult_copepods = mean(prop_adult_copepods),
            avg_prop_copepod_eggs = mean(prop_copepod_eggs), 
            .groups = 'drop')
autoinfection_crabmeans

#plotting means by individual crab
crab_vis_1 <- ggplot(data = autoinfection_crabmeans, 
       aes(x = egg_development_stage, y = avg_prop_viable_eggs, 
           group = 1 ,     # necessary if we don't actually group
           col = "#7F0000"
           #, group = crab_id # this is one way to do it, but decided instead to facet so we can see each indiv crab
           )) + 
  geom_point() +
  geom_line() +
  geom_point(aes(y = avg_prop_nonviable_eggs, col = "#B30000")) +
  geom_line(aes(y = avg_prop_nonviable_eggs, col = "#B30000")) +
  geom_point(aes(y = avg_prop_adult_copepods, col = "#FDD49E")) +
  geom_line(aes(y = avg_prop_adult_copepods, col = "#FDD49E")) +
  geom_point(aes(y = avg_prop_copepod_eggs, col = "#EF6548")) +
  geom_line(aes(y = avg_prop_copepod_eggs, col = "#EF6548")) +
  facet_wrap(vars(crab_id)) +
  scale_color_manual(values = c("#7F0000","#B30000","#FDD49E", "#EF6548"),
                     labels = c("Viable Eggs", "Nonviable Eggs", "Adult Copepods", "Copepod Eggs" ),
                     name = "Legend") +
  theme_gray() +
  ylab("Average Proportion") +
  xlab("Egg Development Stage") + 
  ggtitle("Autoinfection Across Egg Development Stages") +
  theme(plot.title = element_text(hjust = 0.5))


#plotting means by individual crab without viable eggs
crab_vis_2 <- ggplot(data = autoinfection_crabmeans, 
       aes(x = egg_development_stage, y = avg_prop_nonviable_eggs, 
           group = 1 ,     # necessary if we don't actually group
           col = "#B30000"
           #, group = crab_id # this is one way to do it, but decided instead to facet so we can see each indiv crab
           )) + 
  geom_point() +
  geom_line() +
  geom_point(aes(y = avg_prop_adult_copepods, col = "#FDD49E")) +
  geom_line(aes(y = avg_prop_adult_copepods, col = "#FDD49E")) +
  geom_point(aes(y = avg_prop_copepod_eggs, col = "#EF6548")) +
  geom_line(aes(y = avg_prop_copepod_eggs, col = "#EF6548")) +
  facet_wrap(vars(crab_id)) +
  scale_color_manual(values = c("#B30000","#FDD49E", "#EF6548"),
                     labels = c("Nonviable Eggs", "Adult Copepods", "Copepod Eggs" ),
                     name = "Legend") +
  theme_gray() +
  ylab("Average Proportion") +
  xlab("Egg Development Stage") + 
  ggtitle("Autoinfection Across Egg Development Stages") +
  theme(plot.title = element_text(hjust = 0.5))

crab_vis_2
```


## 2.c) Decrease Visualization Complexity 
```{r}


```

